export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';
export const TOGGLE_QUOTE_HIDE = 'TOGGLE_QUOTE_HIDE'
export const TOGGLE_QUOTE_SHOW = 'TOGGLE_QUOTE_SHOW'
export const TOGGLE_QUOTE_FAILED = 'TOGGLE_QUOTE_FAILED'
