version: '3'

services:
  postgres:
    image: 'postgres:10.7-alpine'
    environment:
      POSTGRES_USER: 'devuser'
      POSTGRES_PASSWORD: 'pass'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  api:
    depends_on:
      - 'postgres'
    build: './api'
    env_file:
      - '.env'
    ports:
      - '3001:3001'
    volumes:
      - './api:/api-app'
  client:
    depends_on:
      - 'api'
    build: './client'
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - './client:/client-app'

volumes:
  postgres:
